[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
wybe_launchpad = "8254Y8fZnZN6xsi6xGADpjUDrd78PeQCg6kbfzpRMYPS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"
docker_image = "projectserum/build:v0.24.2"  # Use a supported image

[provider.docker]
image = "backpackapp/build:v0.31.0"



[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
